<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>UrlTrimmer.WebApp</RootNamespace>
      <UserSecretsId>32ca09c8-5d1d-485d-ae94-7fe6388e6753</UserSecretsId>
  </PropertyGroup>
</Project>